# Generated by Django 6.0.5 on 2026-05-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_roll_no', models.IntegerField()),
                ('std_fname', models.CharField(max_length=30)),
                ('std_lname', models.CharField(max_length=30)),
                ('std_class', models.IntegerField()),
            ],
        ),
    ]
