# Generated by Django 6.0.5 on 2026-05-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std_address',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='student',
            name='std_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='std_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='std_phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='std_section',
            field=models.CharField(default='A', max_length=30),
        ),
    ]
